[package]
name = "lobster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
com = "0.6.0"
com_macros = "0.6.0"

#[dependencies.windows]
#version = "0.36.1"
#features = [
#	"Win32_System_Com"
#]

